CREATE TABLE `orders` (
  `order-id` varchar(300) NOT NULL,
  `order-item-id` varchar(300) NOT NULL,
  `purchase-date` date DEFAULT NULL,
  `payments-date` date DEFAULT NULL,
  `buyer-email` text,
  `buyer-name` text,
  `buyer-phone-number` text,
  `sku` text,
  `product-name` text,
  `quantity-purchased` bigint(20) DEFAULT NULL,
  `currency` text,
  `item-price` double DEFAULT NULL,
  `item-tax` double DEFAULT NULL,
  `shipping-price` double DEFAULT NULL,
  `shipping-tax` double DEFAULT NULL,
  `ship-service-level` text,
  `recipient-name` text,
  `ship-address-1` text,
  `ship-address-2` text,
  `ship-address-3` text,
  `ship-city` text,
  `ship-state` text,
  `ship-postal-code` text,
  `ship-country` text,
  `ship-phone-number` text,
  `delivery-start-date` timestamp NULL DEFAULT NULL,
  `delivery-end-date` timestamp NULL DEFAULT NULL,
  `delivery-time-zone` text,
  `delivery-instructions` text,
  `sales-channel` text,
  `is-prime` varchar(100) DEFAULT NULL,
  `seller-id` varchar(1000) NOT NULL,
  `user-id` varchar(1000) NOT NULL,
  `current-timestamp` datetime DEFAULT CURRENT_TIMESTAMP,
  `marketplace-id` varchar(400) DEFAULT NULL,
  PRIMARY KEY (`order-id`,`order-item-id`,`user-id`,`seller-id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
