CREATE TABLE `restock_inventory` (
  `name` text,
  `sku` varchar(300) NOT NULL,
  `asin` varchar(300) DEFAULT NULL,
  `condition` varchar(500) DEFAULT NULL,
  `supplier` text,
  `sales-last-30` double DEFAULT '0',
  `units-last-30` int(11) DEFAULT '0',
  `total-units` int(11) DEFAULT '0',
  `inbound` text,
  `available` text,
  `fc-transfer` text,
  `fc-processing` text,
  `customer-order` text,
  `unfulfillable` text,
  `fulfilled-by` text,
  `days-of-supply` text,
  `alert` text,
  `recommended-order-quantity` text,
  `recommended-order-date` text,
  `user-id` varchar(1000) NOT NULL,
  `seller-id` varchar(1000) DEFAULT NULL,
  `current-timestamp` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `marketplace-id` varchar(400) DEFAULT NULL,
  `price` double DEFAULT '0',
  PRIMARY KEY (`sku`,`user-id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
