CREATE TABLE `settlements` (
  `settlement-id` bigint(20) DEFAULT NULL,
  `settlement-start-date` date DEFAULT NULL,
  `settlement-end-date` date DEFAULT NULL,
  `deposit-date` date DEFAULT NULL,
  `total-amount` double DEFAULT NULL,
  `currency` text,
  `transaction-type` text,
  `order-id` text,
  `merchant-order-id` text,
  `adjustment-id` text,
  `shipment-id` text,
  `marketplace-name` text,
  `amount-type` text,
  `amount-description` text,
  `amount` double DEFAULT '0',
  `fulfillment-id` text,
  `posted-date` text,
  `order-item-code` bigint(20) DEFAULT NULL,
  `merchant-order-item-id` text,
  `merchant-adjustment-item-id` text,
  `sku` text,
  `quantity-purchased` bigint(20) DEFAULT NULL,
  `user-id` text,
  `seller-id` text,
  `current-timestamp` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `marketplace-id` varchar(400) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
